# Generated by Django 4.1.3 on 2022-11-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knbisapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='conent',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='uid',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
