# Generated by Django 4.1.3 on 2022-11-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knbisapp', '0002_rename_conent_todo_content_remove_todo_id_todo_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='uid',
            new_name='id',
        ),
    ]
