# Generated by Django 4.1.3 on 2022-11-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knbisapp', '0003_rename_uid_todo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='content',
            new_name='conent',
        ),
    ]
