# Generated by Django 4.1.3 on 2022-11-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knbisapp', '0004_rename_content_todo_conent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='conent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='id',
            new_name='uid',
        ),
    ]
