# Generated by Django 4.1.3 on 2022-11-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knbisapp', '0005_rename_conent_todo_content_rename_id_todo_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
