# Generated by Django 4.1.3 on 2022-11-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knbisapp', '0006_todo_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
