# Generated by Django 4.1.3 on 2022-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knbisapp', '0007_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='uid',
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
