# Generated by Django 4.1.3 on 2022-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knbisapp', '0008_remove_todo_createdat_remove_todo_uid_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
