# Generated by Django 4.1.3 on 2022-11-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knbisapp', '0009_alter_todo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
